### ISSUE TITLE
[Bug]: Deleted/Despawned Cargo blocks Nodes and Seats

### ISSUE THREAD

**Issue by Lazejun** [official-antistasi-community/A3-Antistasi#2346]
If Cargo in a Vehicle Despawns or gets Deleted all occupied Seats will be blocked and the Node is unuseable, similar to how its supposed to work if Cargo is loaded, but as there is no Cargo you cannot unload it.

**Comment by MeltedPixel** [comment]
Should be fixed in https://github.com/official-antistasi-community/A3-Antistasi/pull/2262

**Comment by Lazejun** [comment]
No

**Comment by Tiny-DM** [comment]
Tested, garaging the loot crate that's inside a vehicle will still block seats. We can probably just use the function to unblock the seats when the vehicle is garaged as I dont think we delete vehicles for any other reason.

**Comment by ante185** [comment]
Not fixed, you can replicate it using the Transfer Vehicle cargo to Ammobox on the arsenal box.
