### ISSUE TITLE
Deduplicate Loot Crate Item Spawning Code

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#433]
See #424 

Issue is essentially we've got a lot of duplicated spawning code, that we could cut down into a function or two.

**Comment by Bob-Murphy** [comment]
This mofo still an issue?

**Comment by HakonRydland** [comment]
fixed with pr#899?

**Comment by Spoffy** [comment]
Not at last check I don't think, but when I next review I'll check for this.

**Comment by Lazejun** [comment]
This is in Theory Closed

**Comment by Bob-Murphy** [comment]
Correct.
The number wasn't properly integrated within #964 to be closed.
Will be reopened if problem still persists.
